<?php
/**
 * News Description Template
 *
 * @var \Vgroup65\News\Block\NewsDescription $block
 */
?>
<script src="https://platform-api.sharethis.com/js/sharethis.js#property=6540e49f744d850019cafc5b&product=inline-share-buttons&source=platform" async="async"></script>

<div class="vgNews">
    <h2><?= $block->escapeHtml(__('News')); ?></h2>

    <div class="vgNews_cats">
        <h2><?= $block->escapeHtml(__('News Category')); ?></h2>
        <?php $newsCategory = $block->getNewsCategory(); ?>
        <a href="<?= $block->escapeUrl($block->getUrl('news')); ?>">
            <?= $block->escapeHtml(__('All News')); ?>
        </a>
        <?php foreach ($newsCategory as $category): ?>
            <a href="<?= $block->escapeUrl($block->getUrl('news/view/category', ['category' => $category['category_url']])); ?>">
                <?= $block->escapeHtml($category['title']); ?>
            </a>
        <?php endforeach; ?>
    </div>

    <div class="vgNews_content">
        <?php $news = $block->getNewsDetail(); ?>
        <?php if ($news->count() == 0): ?>
            <br><br><?= $block->escapeHtml(__('This News no longer exists.')); ?>
        <?php endif; ?>

        <?php foreach ($news as $values): ?>
            <h2 class="title"><?= $block->escapeHtml($values['title']); ?></h2>

            <p class="small">
                <span><?= $block->escapeHtml(date('m/d/Y', strtotime($values['publish_date']))); ?></span>
                <?php if ($values['category_id'] != '0'):
                    $newsCategoryIds = explode(',', $values['category_id']);
                    $categoryData = [];
                    foreach ($newsCategoryIds as $newsCategoryId) {
                        $categoryData[] = $block->getNewsCategoryTitle($newsCategoryId); // returns array
                    }
                    if (!empty($categoryData)): ?>
                        <span class="categories">
                            <?php $i = 0;
                            foreach ($categoryData as $cat):
                                if ($i++ > 0) { echo ', '; } ?>
                                <a href="<?= $block->escapeUrl($block->getUrl('news/view/category', ['category' => $cat['category_url']])); ?>">
                                    <?= $block->escapeHtml($cat['title']); ?>
                                </a>
                            <?php endforeach; ?>
                        </span>
                    <?php endif;
                endif; ?>
            </p>

            <?php if (!empty($values['image'])):
                $newsImage = $values['image'];
                if (!filter_var($newsImage, FILTER_VALIDATE_URL)) {
                    $helper = $block->getHelper();
                    $getBaseUrl = $helper->getBaseUrl();
                    $newsImageSrcValue = $getBaseUrl . '/' . $newsImage;
                } else {
                    $newsImageSrcValue = $newsImage;
                } ?>
                <p>
                    <img
                        alt="<?= $block->escapeHtmlAttr($values['title']); ?>"
                        title="<?= $block->escapeHtmlAttr($values['title']); ?>"
                        src="<?= $block->escapeUrl($newsImageSrcValue); ?>" />
                </p>
            <?php endif; ?>

            <p><?= /* @noEscape */ $block->getCmsFilterContent($values['description']); ?></p>
        <?php endforeach; ?>

        <div class="sharethis-inline-share-buttons"></div>

        <?php if (!empty($values)): ?>
            <?php $preNews = $block->getPreviousNews(['id' => $values['news_id']]); ?>
            <?php if ($preNews): ?>
                <a href="<?= $block->escapeUrl($block->getUrl('news/view/detail', ['news' => $preNews->getUrlIdentifier()])); ?>" class="p_left">
                    <?= $block->escapeHtml(__('Previous')); ?>
                </a>
            <?php endif; ?>

            <?php $nextNews = $block->getNextNews(['id' => $values['news_id']]); ?>
            <?php if ($nextNews): ?>
                <a href="<?= $block->escapeUrl($block->getUrl('news/view/detail', ['news' => $nextNews->getUrlIdentifier()])); ?>" class="n_right">
                    <?= $block->escapeHtml(__('Next')); ?>
                </a>
            <?php endif; ?>
        <?php endif; ?>
    </div>
</div>
