<?php
use Magento\Framework\App\Action\Action;

$productCollection = $block->getProductCollection();
$imageBlock = $block->getLayout()->createBlock(\Magento\Catalog\Block\Product\ListProduct::class);
$showCart = true;
$type = 'widget-new-grid';
$viewMode = 'grid';
$image = 'category_page_grid';
$pos = $block->getPositioned();
?>
<div class="title">
    <strong class="newproduct"><?= $block->escapeHtml(__('New Product')); ?></strong>
</div>

<div class="products-grid">
    <div id="topseller-slider" class="products list items product-items owlslider" data-jcarousel="true">
        <ul class="product-items" id="topsellerowlslider">
            <?php $iterator = 1; ?>
            <?php foreach ($productCollection as $_product): ?>
                <?php
                $productImage = $imageBlock->getImage($_product, $image);
                if ($pos === null) {
                    $position = ' style="left:' . (int) $productImage->getWidth() . 'px; top:' . (int) $productImage->getHeight() . 'px;"';
                }
                ?>
                <?= ($iterator++ == 1) ? '<li class="product-item"><div class="product-item-info">' : '</div></li><li class="product-item"><div class="product-item-info">' ?>
                
                <a href="<?= $block->escapeUrl($_product->getProductUrl()); ?>">
                    <?= /* @noEscape */ $productImage->toHtml() ?>
                </a>

                <div class="product details product-item-details">
                    <strong class="product name product-item-name">
                        <a class="product-item-link" href="<?= $block->escapeUrl($_product->getProductUrl()); ?>">
                            <?= $block->escapeHtml($_product->getName()); ?>
                        </a>
                    </strong>

                    <?php if ($showCart): ?>
                        <?= /* @noEscape */ $block->getProductPricetoHtml($_product, $type); ?>
                        <?= /* @noEscape */ $block->getProductDetailsHtml($_product); ?>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions">
                                <div class="actions-primary"<?= strpos((string)$pos, $viewMode . '-primary') ? $block->escapeHtmlAttr($position) : ''; ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" action="<?= $block->escapeUrl($postParams['action']); ?>" method="post">
                                            <input type="hidden" name="product" value="<?= $block->escapeHtmlAttr($postParams['data']['product']); ?>">
                                            <input type="hidden" name="<?= $block->escapeHtmlAttr(Action::PARAM_NAME_URL_ENCODED); ?>" value="<?= $block->escapeHtmlAttr($postParams['data'][Action::PARAM_NAME_URL_ENCODED]); ?>">
                                            <?= $block->getBlockHtml('formkey'); ?>
                                            <button type="submit"
                                                    title="<?= $block->escapeHtml(__('Add to Cart')); ?>"
                                                    class="action tocart primary">
                                                <span><?= $block->escapeHtml(__('Add to Cart')); ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <div class="stock available">
                                                <span><?= $block->escapeHtml(__('In stock')); ?></span>
                                            </div>
                                        <?php else: ?>
                                            <div class="stock unavailable">
                                                <span><?= $block->escapeHtml(__('Out of stock')); ?></span>
                                            </div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>

                                <div class="actions-secondary" data-role="add-to-links">
                                    <?php if ($block->helper(\Magento\Wishlist\Helper\Data::class)->isAllow()): ?>
                                        <a href="#"
                                           data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_product); ?>'
                                           class="action towishlist" data-action="add-to-wishlist"
                                           title="<?= $block->escapeHtml(__('Add to Wish List')); ?>">
                                            <span><?= $block->escapeHtml(__('Add to Wish List')); ?></span>
                                        </a>
                                    <?php endif; ?>

                                    <?php $compareHelper = $block->helper(\Magento\Catalog\Helper\Product\Compare::class); ?>
                                    <a href="#"
                                       class="action tocompare"
                                       data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_product); ?>'
                                       title="<?= $block->escapeHtml(__('Add to Compare')); ?>">
                                        <span><?= $block->escapeHtml(__('Add to Compare')); ?></span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>

                <?= ($iterator == count($productCollection) + 1) ? '</div></li>' : '' ?>
            <?php endforeach; ?>
        </ul>
    </div>
</div>

<?php if (!$block->isRedirectToCartEnabled()): ?>
    <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
    </script>
<?php endif; ?>
